name: Django CI/CD

on:
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: 1
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mahmadi1600/blog-workflow
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mahmadi1600
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build the docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mahmadi1600/blog-workflow:v1

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: deploying in HamRavesh
          run: |
            curl -X PUT 'https://api.console.hamravesh.ir/api/v1/darkube/apps/update_from_cli/' \
            -H 'Content-Type: application/json' \
            -d '{
              "trigger_deploy_token": "${{secrets.DEPLOY_TOKEN_BLOG_APP_WORKFLOW_DANAJOU_BLOG_HAMRAVESH_C13}}", 
              "app_id": "${{secrets.APP_ID_BLOG_APP_WORKFLOW_DANAJOU_BLOG_HAMRAVESH_C13}}",
              "image_tag": "v1"
              }'