name: Django CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: 81.12.30.45
      POSTGRES_PORT: 27848
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: 1
      ALLOWED_HOSTS: '*'
      DATABASE_URL: postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@81.12.30.45:27848/postgres
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.1'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test


  darkube_build_blog_danajou-workflow_hamravesh-c13:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: mahmadi1600/blog-workflow
    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./Dockerfile
        --build-context . '
  darkube_deploy_blog_danajou-workflow_hamravesh-c13:
    runs-on: ubuntu-latest
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_blog_danajou-workflow_hamravesh-c13
    steps:
    - name: darkube-cli deploy
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_BLOG_DANAJOU_WORKFLOW_HAMRAVESH_C13}}
        --app-id ${{secrets.APP_ID_BLOG_DANAJOU_WORKFLOW_HAMRAVESH_C13}} --image-tag
        ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}